export const ROLES = {
  ADMIN: "ADMIN",
  PLANNER: "PLANNER",
  PRODUCTION_MANAGER: "PRODUCTION_MANAGER",
  OPERATOR: "OPERATOR",
  QUALITY_STAFF: "QUALITY_STAFF",
  VIEWER: "VIEWER"
};

export const ROLE_LABELS = {
  ADMIN: "Admin",
  PLANNER: "Planlama",
  PRODUCTION_MANAGER: "Üretim Yöneticisi",
  OPERATOR: "Operatör",
  QUALITY_STAFF: "Kalite Personeli",
  VIEWER: "İzleyici"
};

export const ROLE_GROUPS = {
  dashboard: [ROLES.ADMIN, ROLES.PLANNER, ROLES.PRODUCTION_MANAGER, ROLES.QUALITY_STAFF, ROLES.VIEWER],
  planningWork: [ROLES.PLANNER],
  shiftPlanningWork: [ROLES.PLANNER, ROLES.PRODUCTION_MANAGER],
  operationsManagement: [ROLES.PRODUCTION_MANAGER],
  operationsAndQuality: [ROLES.PRODUCTION_MANAGER, ROLES.QUALITY_STAFF],
  qualityWork: [ROLES.QUALITY_STAFF],
  adminDefinitions: [ROLES.ADMIN],
  masterData: [ROLES.ADMIN, ROLES.PLANNER, ROLES.PRODUCTION_MANAGER],
  reports: [ROLES.ADMIN, ROLES.PLANNER, ROLES.PRODUCTION_MANAGER, ROLES.QUALITY_STAFF, ROLES.VIEWER],
  allAuthenticated: [ROLES.ADMIN, ROLES.PLANNER, ROLES.PRODUCTION_MANAGER, ROLES.OPERATOR, ROLES.QUALITY_STAFF, ROLES.VIEWER],

  management: [ROLES.ADMIN, ROLES.PLANNER, ROLES.PRODUCTION_MANAGER, ROLES.VIEWER],
  managementPlusQuality: [ROLES.ADMIN, ROLES.PLANNER, ROLES.PRODUCTION_MANAGER, ROLES.QUALITY_STAFF, ROLES.VIEWER],
  planning: [ROLES.PLANNER],
  production: [ROLES.PRODUCTION_MANAGER, ROLES.OPERATOR],
  quality: [ROLES.QUALITY_STAFF],
  adminOnly: [ROLES.ADMIN]
};

export function hasRole(user, allowedRoles) {
  return Boolean(user?.role && allowedRoles.includes(user.role));
}
