import { Router } from "express";
import { authRoutes } from "../modules/auth/auth.routes.js";
import { dashboardRoutes } from "../modules/dashboard/dashboard.routes.js";
import { machineRoutes } from "../modules/machines/machine.routes.js";
import { productionLineRoutes } from "../modules/production-lines/productionLine.routes.js";
import { productionAlertRoutes } from "../modules/production-alerts/productionAlert.routes.js";
import { productionLogRoutes } from "../modules/production-logs/productionLog.routes.js";
import { productRouteRoutes } from "../modules/product-routes/productRoute.routes.js";
import { productRoutes } from "../modules/products/product.routes.js";
import { qualityCheckRoutes } from "../modules/quality-checks/qualityCheck.routes.js";
import { reportRoutes } from "../modules/reports/report.routes.js";
import { shiftRoutes } from "../modules/shifts/shift.routes.js";
import { userRoutes } from "../modules/users/user.routes.js";
import { workOrderOperationRoutes } from "../modules/work-order-operations/workOrderOperation.routes.js";
import { workOrderRoutes } from "../modules/work-orders/workOrder.routes.js";

export const apiRoutes = Router();

apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
apiRoutes.use("/machines", machineRoutes);
apiRoutes.use("/production-lines", productionLineRoutes);
apiRoutes.use("/production-alerts", productionAlertRoutes);
apiRoutes.use("/production-logs", productionLogRoutes);
apiRoutes.use("/product-routes", productRouteRoutes);
apiRoutes.use("/products", productRoutes);
apiRoutes.use("/quality-checks", qualityCheckRoutes);
apiRoutes.use("/reports", reportRoutes);
apiRoutes.use("/shifts", shiftRoutes);
apiRoutes.use("/users", userRoutes);
apiRoutes.use("/work-order-operations", workOrderOperationRoutes);
apiRoutes.use("/work-orders", workOrderRoutes);
